default: dw


idl:
        python3 util.py -c idl -t dart -s ../proto -o ./lib/models/idl/
lib:
        python3 util.py -c lib -t debug -i ../sdk

deploy:
        python3 util.py -c lib -t release -i ../sdk

dw:
        flutter run -d windows
dm:
        flutter run -d macos

build:
        python3 util.py -c build

json:
    flutter packages pub run build_runner build
