[workspace]
members = [
        "app",
        "base",
        "calendar",
        "common",
        "setting",
        "gateway",
        "im",
        "migration",
        "office",
        "proto",
        "rtc",
        "store",
        "todo",
        "user",
]
resolver = "2"

[workspace.dependencies]
anyhow = "1"
async-trait = "0.1.74"
axum = { version = "0.8.3", features = ["multipart"] }
axum-server = { version = "0.7.2", features = ["tls-rustls-no-provider"] }
chrono = "0.4"
dashmap = "6.1.0"
fluent-templates = { version = "0.9.4", features = ["tera"] }
futures = "0.3"
futures-util = "0.3.28"
include_dir = "0.7"
image = "0.25"
imageproc = "0.25"
ab_glyph = "0.2.30"
loco-rs = { version = "0.16.4", features = [] }
mimalloc = "0.1.47"
moka = {version = "0.12.0", features = ["future"] }
parking_lot = "0.12"
prost = { version = "0.13", features = ["derive"] }
rand = "0.8.5"
redis = { version = "0.27.6", features = ["aio", "connection-manager", "tokio-comp"] }
scopeguard = "1.2.0"
sea-orm = { version = "1.1.20", features = [
  "sqlx-sqlite",
  "sqlx-postgres",
  "runtime-tokio-rustls",
  "macros",
] }
sea-query = "0.32.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
strum = { version = "*", features = ["derive"]}
tokio = { version = "1.33.0", default-features = false }
tokio-stream = "0.1"
tokio-util = { version = "0.7.10", features = ["full"] }
tokio-tungstenite = { version = "0.26.0" }
tower-http = "*"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"] }
tracing = "0.1.40"
tungstenite = { version = "0.26.0" }
unic-langid = "0.9.4"
uuid = { version = "1.6.0", features = ["v4"] }
validator = { version = "0.20" }
vecbool = { path = "../tool/vecbool" }
warp = { version = "0.3", features = ["tls"] }
yrs = "0.18"
yrs-axum = "0.8.2"

base = { path = "./base" }
calendar = { path = "./calendar" }
common = { path = "./common" }
setting  = { path = "./setting" }
gateway = { path = "./gateway" }
im = { path = "./im" }
migration = { path = "./migration" }
office = { path = "./office" }
proto = { path = "./proto" }
rtc = { path = "./rtc" }
todo = { path = "./todo" }
user = { path = "./user" }
store = { path = "./store" }

# = { workspace = true }