//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "calendars")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub creator: i64,
    pub tenant_id: i64,
    pub public: bool,
    pub is_defalut: bool,
    pub color: i32,
    pub name: Option<String>,
    pub desc: Option<String>,
    pub version: i64,
    #[sea_orm(column_type = "JsonBinary")]
    pub subscriber: Json,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub extra: Vec<u8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
