//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "chats")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub r#type: i16,
    pub status: i16,
    pub name: String,
    pub owner_id: i64,
    pub peer_a_id: i64,
    pub peer_b_id: i64,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub cmv: Vec<u8>,
    pub last_message_id: i64,
    pub last_message_pos: i32,
    pub last_message_badge: i32,
    pub admin_ids: Vec<i64>,
    pub version: i64,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub extra: Vec<u8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
