//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "cycleds")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub calendar_id: i64,
    pub start_at: i64,
    pub stop_at: i64,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub rule: Vec<u8>,
    pub exceptions: Vec<i64>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub template: Vec<u8>,
    pub version: i64,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub extra: Vec<u8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
