//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "feeds")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub entity_id: i64,
    pub entity_type: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: i64,
    pub refer_id: i64,
    pub refer_pos: i32,
    pub refer_badge: i32,
    pub read_pos: i32,
    pub read_badge: i32,
    pub update_ms: i64,
    pub rank_time_ms: i64,
    pub status: i32,
    pub is_mute: i32,
    pub is_top: i32,
    pub version: i64,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub extra: Vec<u8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
