//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "meetings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique)]
    pub room_id: String,
    pub title: String,
    pub host_id: i64,
    pub password: Option<String>,
    pub status: i16,
    pub scheduled_at: Option<i64>,
    pub started_at: i64,
    pub ended_at: Option<i64>,
    pub tenant_id: i64,
    pub max_participants: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub settings: Json,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
