//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "messages")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub r#type: i16,
    pub chat_id: i64,
    pub from_id: i64,
    pub pos: i32,
    pub badge: i32,
    pub status: i16,
    pub client_id: i64,
    pub at_user_ids: Vec<i64>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub content: Vec<u8>,
    pub summary: String,
    pub version: i64,
    pub cmv_id: i64,
    pub cmv_count: i32,
    pub read_count: i32,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub read_states: Vec<u8>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub reactions: Vec<u8>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub extra: Vec<u8>,
    pub ref_message_id: i64,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub ref_data: Vec<u8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
