//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod accounts;
pub mod calendars;
pub mod chats;
pub mod cmvs;
pub mod cycleds;
pub mod depts;
pub mod feeds;
pub mod messages;
pub mod pipelines;
pub mod schedule_reminders;
pub mod schedules;
pub mod settings;
pub mod tenants;
pub mod user2_calendars;
pub mod users;
