//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod accounts;
pub mod calendars;
pub mod meeting_members;
pub mod meetings;
pub mod chats;
pub mod cmvs;
pub mod cycleds;
pub mod depts;
pub mod document_members;
pub mod document_shares;
pub mod document_spaces;
pub mod document_stars;
pub mod document_versions;
pub mod document_mentions;
pub mod document_visits;
pub mod documents;
pub mod feeds;
pub mod files;
pub mod messages;
pub mod pipelines;
pub mod schedule_reminders;
pub mod schedules;
pub mod settings;
pub mod tenants;
pub mod user2_calendars;
pub mod users;
pub mod wiki_members;
pub mod wiki_pins;
pub mod wikis;
