//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "market_info")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub app_id: i64,
    pub app_category: String,
    pub icon_file_id: Option<i64>,
    pub screenshots: Vec<i64>,
    pub short_description: String,
    pub detailed_description: Option<String>,
    pub developer_name: String,
    pub developer_email: String,
    pub support_url: String,
    pub homepage_url: String,
    pub permissions: Vec<String>,
    pub install_count: i32,
    pub rating_avg: f64,
    pub rating_count: i32,
    pub is_featured: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
