//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "schedules")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub calendar_id: i64,
    pub r#type: i32,
    pub tenant_id: i64,
    pub owner: i64,
    pub cycle_rule_id: i64,
    pub cycle_end_time: i64,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub extra: Vec<u8>,
    pub title: String,
    pub exception: bool,
    pub full_day: bool,
    pub show_as_idle: bool,
    pub public_permission: i32,
    pub start_time: i64,
    pub end_time: i64,
    pub member_count: i32,
    pub member_ids: Vec<i64>,
    pub version: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
