[package]
name = "office"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { workspace = true }
tokio = { workspace = true }
tower-http = { workspace = true }
yrs = { workspace = true }
futures-util = { workspace = true }
yrs-axum = { workspace = true }
loco-rs = { workspace = true }
rust-embed = { workspace = true }
mime_guess = { workspace = true }

common = { workspace = true }
base = { workspace = true }
proto = { workspace = true }
prost = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
rand = { workspace = true }
bcrypt = "0.15"