[package]
name = "user"
version = "0.1.0"
edition = "2024"

[dependencies]
loco-rs = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
proto = { workspace = true }
tracing = { workspace = true }
tokio-util = { workspace = true }
tokio = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
prost = { workspace = true }

common = { workspace = true }
base = { workspace = true }