[package]
name = "proto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "*"
prost = "0.13"
prost-types = "0.13"
serde = { workspace = true }
shadow-rs = { version = "1.4", default_features = false, features = ["build"] }

[build-dependencies]
prost-build = "0.13"
prost-build-config = { workspace = true }
serde_yaml = "0.9.33"
shadow-rs = "1.4"