syntax = "proto3";
package command;
option go_package = "./proto";

enum Command {
    COMMAND_UNKNOWN = 0;
    // basic
    ACK = 1;
    ECHO = 2;

    SDK_INIT = 1000;
    USER_LOGIN = 1001;
    USER_LOGOUT = 1002;
    SDK_GET_VERSION = 1003;
    SDK_GET_DEVICE_ID = 1004;
    PUSH_KICKOFF = 1005;
    SDK_WRITE_LOG = 1006;
    UPLOAD_LOG = 1007;
    NET_REQUEST = 1008;
    PUSH_NOTICE = 1009;


    PIPELINE_PULL_PACKET = 1050;
    PIPELINE_PULL_ENTITY = 1051;
    PUSH_SETTING = 1052;
    SETTING_GET_BY_TYPE = 1053;
    SETTING_GET_BY_CURSOR = 1054;
    SETTING_GET_ALL = 1055;
    SETTING_UPDATE = 1056;
    PUSH_ENTITY_CHANGE = 1057;

    FEED_GET_LIST = 1100;
    CHAT_CREATE = 1101;
    CHAT_ENTER = 1102;
    CHAT_ADD_CHATTERS = 1104;
    CHAT_DELETE_CHATTERS = 1105;
    CHAT_UPDATE = 1106;
    CHAT_GET_CHATTERS = 1107;
    CHAT_GET_CHATTER_BY_IDS = 1108;
    CHAT_GET_BY_IDS = 1109;
    CHAT_DISMISS = 1110;
    PUSH_FEED_LIST = 1111;
    CHAT_SET_DRAFT = 1112;
    CHAT_GET_DRAFT = 1113;
    FEED_REMOVE = 1114;
    FEED_SET_TOP = 1115;
    FEED_GET_TOP_LIST = 1116;
    // PUSH_FEED_TOP_LIST = 1117;
    FEED_ACTIVE = 1118;
    CHAT_QUIT = 1119;
    FEED_GET_BY_IDS = 1120;
    FEED_SET_MUTE = 1121;


    MESSAGE_CREATE_DRAFT = 1200;
    MESSAGE_DELETE_DRAFT = 1201;
    MESSAGE_GET_ALL_DRAFTS = 1202;
    MESSAGE_SEND = 1203;
    MESSAGE_RESEND = 1204;
    MESSAGE_RECALL = 1205;
    MESSAGE_DELETE = 1206;
    MESSAGE_GET_BY_POS = 1207;
    MESSAGE_GET_BY_IDS = 1208;
    MESSAGE_READ = 1209;
    // MESSAGE_GET_READSTATE = 1210;
    PUSH_MESSAGES = 1211;
    PUSH_MESSAGE_READSTATE = 1212;
    MESSAGE_GET_BY_RANGE = 1213;
    REACTION_SET = 1214;
    PUSH_REACTIONS = 1215;

    USER_GET_BY_IDS = 1300;
    USER_UPDATE = 1301;
    PUSH_USER_INFO = 1302;

    DEPT_GET_BY_ID = 1350;

    SEARCH_USER = 1400;
    SEARCH_MESSAGE = 1401;
    SEARCH_CHAT = 1402;

    FAVORITE_ADD = 1500;
    FAVORITE_REMOVE = 1501;
    FAVORITE_GET_LIST = 1502;

    // calendar: 1600 ~ 1799
    CALENDAR_GET_LIST = 1600;
    CALENDAR_CREATE = 1601;
    CALENDAR_UPDATE = 1602;
    CALENDAR_DELETE = 1603;
    CALENDAR_SEARCH = 1604;
    CALENDAR_SUBSCRIBE = 1605;
    CALENDAR_PUSH_LIST = 1606;
    CALENDAR_PUSH_UPDATE = 1607;

    SCHEDULE_CREATE = 1610;
    SCHEDULE_REMOVE = 1611;
    SCHEDULE_UPDATE = 1612;
    SCHEDULE_PULL_BY_IDS = 1613;
    SCHEDULE_PULL_BY_CALENDAR_IDS = 1614;
    SCHEDULE_PULL_BUSY = 1615;
    SCHEDULE_PUSH_UPDATE = 1616;
}
