// This file initializes the dynamic library and connects it with the stub
// generated by flutter_rust_bridge_codegen.

import 'dart:ffi';
import 'dart:ffi' as ffi;
import 'dart:isolate';
import 'dart:typed_data';

import 'package:fixnum/fixnum.dart' as $fixnum;
import 'package:ffi/ffi.dart';
import 'package:buzzing/idl/sdk.pb.dart';
import 'package:buzzing/idl/command.pb.dart';
import 'package:flutter/widgets.dart';
import 'package:channel/channel.dart';

import 'gen_ffi_cpp.dart';
// Re-export the bridge so it is only necessary to import this file.
export 'gen_ffi_cpp.dart';
import 'dart:io' as io;

const _base = 'buzzing';

// On MacOS, the dynamic library is not bundled with the binary,
// but rather directly **linked** against the binary.
final _dylib = io.Platform.isWindows ? '$_base.dll' : 'lib$_base.so';

class BuzzingImpl {
  late BuzzingLib lib_;
  static Map<int, Channel<Uint8List>> invokeMap =
      Map<int, Channel<Uint8List>>();
//  Allocator allocator = Allocator();
  static late Channel<Uint8List> pushCh;

  BuzzingImpl(DynamicLibrary lib) {
    lib_ = BuzzingLib(lib);
  }

  void onPushHandler(Pointer<Char> data, int len) {
    var list = Uint8List(len);
    for (int i = 0; i < len; i++) {
      list[i] = data[i];
    }
    print("onPushHandler, ${len}, ${list}, ${data}");
    SdkPushPacket push = SdkPushPacket.fromBuffer(list);
    print("onPushHandler, ${push.command}, ${push.seq}");
    lib_.buzzing_release(data, 0);
  }

  void onInvokeHandler(Pointer<Char> data, int len) {
    var list = Uint8List(len);
    for (int i = 0; i < len; i++) {
      list[i] = data[i];
    }
    InvokeResponse resp = InvokeResponse.fromBuffer(list);
    //resp.fromBbuffer(list);
    print("onInvokeHandler, ${resp.seq}");
    //return;
    final ch = invokeMap[resp.seq];
    ch?.send(list);
    ch?.close();
    invokeMap.remove(resp.seq);
  }

  int invoke_seq = 1;
  late NativeCallable<ResultCallbackFunction> invokeCallback;
  late NativeCallable<BuzzingPushHandlerFunction> pushCallback;

  Future<int> initSdk(Uint8List data) async {
    final data_ptr = calloc<Char>(data.length);
    for (int i = 0; i < data.length; i++) {
      data_ptr[i] = data[i];
    }
    pushCallback =
        NativeCallable<BuzzingPushHandlerFunction>.listener(onPushHandler);
    invokeCallback =
        NativeCallable<ResultCallbackFunction>.listener(onInvokeHandler);
    lib_.buzzing_init(data_ptr, data.length, pushCallback.nativeFunction,
        invokeCallback.nativeFunction);
    calloc.free(data_ptr);
    return 0;
  }

  Future<Uint8List> invokeAsync(int command, Uint8List data) async {
    Channel<Uint8List> ch = Channel<Uint8List>();
    invokeMap[invoke_seq] = ch;
    print("invoke async, command: ${command}");

    final data_ptr = calloc<Char>(data.length);
    for (int i = 0; i < data.length; i++) {
      data_ptr[i] = data[i];
    }

    lib_.buzzing_invoke(data_ptr, data.length);
    calloc.free(data_ptr);
    invoke_seq = invoke_seq + 1;
    final ret = Uint8List(0);
    final d = await ch.receive();
    if (!d.isClosed) {
      print("invoke async done, command: ${command}");
      return d.data ?? ret;
    }
    print("invoke callback ch closed");
    return ret;
  }

  Stream<Uint8List> registerEventHandler() async* {
    pushCh = Channel<Uint8List>();
    final d = await pushCh.receive();
    final ret = Uint8List(0);
    while (!d.isClosed) {
      yield d.data ?? ret;
    }
    yield ret;
  }
}

final BuzzingImpl api = BuzzingImpl(io.Platform.isIOS || io.Platform.isMacOS
    ? DynamicLibrary.executable()
    : DynamicLibrary.open(_dylib));
