[package]
name = "rtc"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
axum = { workspace = true, features = ["ws"] }
axum-server = { workspace = true }
futures-util = { workspace = true }
loco-rs = { workspace = true }
prost = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tokio-stream= { workspace = true }
uuid = { version = "1.6.0", features = ["v4"] }
webrtc = "0.14.0"
hmac = "0.12"
sha2 = "0.10"
base64 = "0.22"
bcrypt = "0.15"

sea-orm = { workspace = true }

base = { workspace = true }
common = { workspace = true }
proto = { workspace = true }
