// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiFlutterGreet(name: name);

String greet2({required String name}) =>
    RustLib.instance.api.crateApiFlutterGreet2(name: name);

int buzzingInit({required List<int> param}) =>
    RustLib.instance.api.crateApiFlutterBuzzingInit(param: param);

int buzzingInvoke({required List<int> param}) =>
    RustLib.instance.api.crateApiFlutterBuzzingInvoke(param: param);

Stream<Uint8List> buzzingRegPushHandler() =>
    RustLib.instance.api.crateApiFlutterBuzzingRegPushHandler();

Stream<Uint8List> buzzingRegInvokeHandler() =>
    RustLib.instance.api.crateApiFlutterBuzzingRegInvokeHandler();
