name: buzzing_sdk_test
description: Pure Dart integration tests for the Buzzing Rust SDK via FRB.
publish_to: none
environment:
  sdk: ^3.9.2

dependencies:
  flutter_rust_bridge: 2.11.1
  fixnum: ^1.1.0
  protobuf: ^4.2.0

dev_dependencies:
  test: ^1.25.0
